version: "3"
services:
  redis:
    image: redis
    restart: always
    volumes:
    - /home/ec2-user/redis:/data
    ports:
      - 6379:6379
    command: redis-server --appendonly yes

  springbootapp:
    build: .
    ports:
      - 8080:8080
    volumes:
      - /home/ec2-user/logs:/logs
    depends_on:
      - redis
